config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"

  resources :books
  # For details on# the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord


  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def show
       @book = Book.find(params[:id])

    end

    def index
       @books = Book.all
       @book = Book.new
    end

    def edit
      @book = Book.find(params[:id])

    end

    def destroy
      book = Book.find(params[:id])
      book.destroy
      redirect_to '/books'
    end

    def update
      @book = Book.find(params[:id])

      if @book.update(book_params)

        flash[:notice]="Book was successfully updated."
        redirect_to book_path(@book)
      else
        render :edit
      end
    end
    def create
     @book = Book.new(book_params)
     if @book.save
       flash[:notice]="Book was successfully created."
      redirect_to book_path(@book)
     else
        @books = Book.all
         render :index
     end
    end







    private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<!--編集-->
<!--<%#= notice %>-->
<p id="notice"><%= flash[:notice] %></p>

<h1>Editing Book</h1>
<!--ここに同じくindexとおなじように記入していく-->
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  　<% end %>
  </ul>
<% end %>

  <%= form_with model: @book, local:true do |f| %>

  <p>title<%= f.text_field :title %></p>


  <p>body<%= f.text_area :body %></p>

<%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Show",book_path(@book.id) %>
|
<%= link_to "back",books_path %>


<!--<form class="edut_book" id="edit_book_51002" action="/books/51002" accept-charest="utf-8" method="post">-->
<!--    <input name="utf8" type="hidden" value="✓">-->
<!--    <input type="hidden" name="authenticity_token" value="rkQPSt8WOo9x3k3Ir9sBxBD8KdPN44p7Kkp+WFbIMNi/mHQCElmurXyY+LebHJ/kW1tULO8hPdV8H31s7adDtA==">-->
<!--    <div class="field">-->
<!--      <label for="book_title">Title</label>-->
<!--      <input class="book_title" type="text" value="リーダブルコード" name="book[title]" id="book_title">-->
<!--    </div>-->

<!--    <div class="field">-->
<!--      <label for="book_body">Body</label-->
<!--      <textarea class="book_body" name="book[body]" id="book_body">-->

<!--      </textarea>-->
<!--    </div>-->
<!--    <div class="action">-->
<!--      <input type="submit" name="commit" value="Update book" data-disable-with="Update Book">-->
<!--    </div>-->

<!--</form>-->

<!--  <br><a class="show_51002" href="/books/51002">Show</a>-->

<!--|-->

<!--  <a class="back" href="/books">Back</a>-->

app/views/books/index.html.erb
<p id="notice"></p>
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

    <% @books.each do |book| %>
    <tr>
      <td>
       <span><%= book.title %></span>
      </td>
      <td>
        <span><%= book.body %></span>
      </td>

  <td><%= link_to "Show",book_path(book.id)%></tb>
  <td><%= link_to "Edit",edit_book_path(book.id)%></td>
  <td><%= link_to "Destroy",book_path(book.id),method: :delete%></td>

</tr>
    <% end %>

  </tbody>
</table>

<h2>New book</h2>

<!--ここにtitleかbodyあるいはその両方記入してない場合記入するような表示をする-->
<!--Title can't be blank-->
<!--Body can't be blank-->

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  　<% end %>
  </ul>
<% end %>

<%= form_with model: @book, local:true do |f| %>
<div>Title</div>
<%= f.text_area :title %>
<div>Body</div>
<%= f.text_area :body %>

<div><%= f.submit 'Create Book' %><div>

  <!--<% flash.each do |key, value| %>-->
  <!--  <p class="alert alert-<%= key %>">-->
  <!--    <%= value %>-->
  <!--  </p>-->
  <!--<% end %>-->


<% end %>

app/views/books/show.html.erb
<%#= notice %>
<p id="notice"><%= flash[:notice] %></p>

<p>
  <div><strong>title:</strong><%= @book.title %></div>
　<div><strong>body:</strong><%= @book.body %></div>
</p>


<%= link_to "Edit",edit_book_path(@book.id) %>

<!--<a class="back" href="/books">Back</a>-->
<%= link_to "back" ,books_path %>

app/views/homes/top.html.erb
<h1>
  ようこそ<strong>Bookers</strong>へ！
</h1>
<p>
   <p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます</p>

  <!--<p><a href="/books">start</a></p>-->
  <%= link_to "back" ,books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>